### ISSUE TITLE
Report joint probability of solution, and next best solution

### ISSUE THREAD

**Issue by cmungall** [INCATools/boomer#153]
* report Pr1*Pr2*...*Pr_n for the selected solution
 * also report same number for 2nd best, or M best solutions

We can also give an ad-hoc confidence score which is the probability of the selected solution divided by the next best (infinite if there is only one solution). Intuitively, if the two best solutions are close we have lower confidence, if it's 100x more likely we can have high confidence.

Note that we can also obtain a more accurate estimation of the probability by dividing the probability of a solution by the sum of all probabilities of all solutions. This will be higher than the simple joint probability when there are cases where solutions have a posterior probability of zero ie unsats. 

As a trivial example, given an ontology

    A Equiv B

and prior probabilities

    Pr(A Equiv B) = 0.1

naive calculation gives Pr=0.1 for the full ontology. However, there are no other possibilities so we are forced to update our prior belief

**Comment by balhoff** [comment]
It's pretty easy for the greedy runs, but now I'm looking into how to do it for the exhaustive search.

**Comment by balhoff** [comment]
The main request here was addressed by #271.
