### ISSUE TITLE
Explain what boomer does in a leading paragraph?

### ISSUE THREAD

**Issue by ddooley** [INCATools/boomer#191]
I kind of get that this tool is an entity mapper between 2 ontologies?  Does it also report on logical inconsistencies when it is 100% sure of an entity match?

**Comment by balhoff** [comment]
@ddooley thanks—I added a paragraph to the beginning of the [README](https://github.com/INCATools/boomer/blob/master/README.md). Is it helpful? I plan to fill out the README further with a specific example, but it's not quite there yet.

**Comment by ddooley** [comment]
Ok, that helps.  One more q: what is a "clique"? A set of logically consistent statements?

**Comment by balhoff** [comment]
A clique is a group of overlapping mappings which interact with each other when selecting logical interpretations.
