### ISSUE TITLE
Add instructions for post-processing output axioms with ROBOT

### ISSUE THREAD

**Issue by balhoff** [INCATools/boomer#44]
Equivalence mappings are represented as mutual subclass axioms in whelk. ROBOT can be used to generate OWL equivalentClass axioms.

See #39.

**Comment by cmungall** [comment]
`robot reason -A "EquivalentClass SubClass" -i output.ofn -s true -o output-normalized.ofn`

be awesome if this wasn't necessary though :-) 

and in future we may want to annotate the output axioms, I don't think robot will propagate
